services:
  app:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile.dev
      target: development
    container_name: noirhotel_app
    ports:
      - "8000:8000"
      - "5173:5173"
    volumes:
      - ../:/var/www/html:cached
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: noir
      DB_USERNAME: ultraego
      DB_PASSWORD: ""
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: noirhotel_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: noir
      MYSQL_USER: ultraego
      MYSQL_PASSWORD: ""
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  dbdata:
